### ISSUE TITLE
README doesn't capture all first time setup steps

### ISSUE THREAD

**Issue by erik** [erik/strava-heatmap-proxy#1]
@chen-ye ran into issues with `STRAVA_ID` not being defined. Seems there's a circular dependency in trying to deploy a worker which references a nonexistent kv secret.

**Comment by qbsho** [comment]
is there a solution for that?

**Comment by qbsho** [comment]
Also the set `account_id` is missing in the init setup

**Comment by erik** [comment]
@xxseabxx I think if you go to the settings page for your worker on dash.cloudflare.com and manually create the `STRAVA_ID` and `STRAVA_COOKIES` environment variables in the UI it should work.

Here's the bug report on the wrangler project with a workaround (using `globalThis.STRAVA_ID`): https://github.com/cloudflare/wrangler/issues/1418
