### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by megavolts** [erik/strava-heatmap-proxy#6]
I was wondering if someone built a docker wrapper around this proxy to automate the process, and ease the deployment?

**Comment by erik** [comment]
Not to my knowledge. Do CloudFlare Workers support Docker images now? 

Have you run into problems following ["the easy way"](https://github.com/erik/strava-heatmap-proxy#the-easy-way) from the README? Should be pretty quick

**Comment by megavolts** [comment]
I did, just add to learn about wrangler and co.
I was just wondering, because I run a unraid server for a bunch of apps, and deploying a container is the easy way.

**Comment by erik** [comment]
Fair enough. The code is a pretty  barebones HTTP proxy and doesn't really use much Cloudflare-specific stuff that would lock it in. Should be straightforward to port it over to a Deno or Node runtime, which could then be containerized.
