### ISSUE TITLE
how to access heatmaps for more sports?

### ISSUE THREAD

**Issue by ghost** [erik/strava-heatmap-proxy#7]
Hi, I've been using this tool for a few months. It's working very nicely and it's extremely convenient.

I just realised that the Strava Heatmap has a lot more than `all`, `ride`, `winter`, `run`, `water` as activity types. The activity types can be seen in the menus on the website: https://www.strava.com/maps/global-heatmap
For example, there's a distinct Trail Run heatmap.
I've tried replacing "run" into "TrailRun" or "trailrun" but it's not working.
Do you know how to access all those extra heatmaps?

Many thanks for your work.

**Comment by erik** [comment]
Thanks for the heads up! I missed that update. 

Seems like they updated the names somewhat. Quickly poking around at the network inspector while trying out the different activity types, I see:

- `sport_TrailRun`
- `sport_GravelRide`
- `sport_Walk`
- etc.

Give that a try?

Also, I no longer have a premium account, would you be able to confirm if the same naming convention now exists for the personal heatmap as well? You can confirm by looking at any of the PNG tile URLs in your browser's network inspector dev tools.

**Comment by ghost** [comment]
Thank you very much for the quick response. I should have been able to figure that myself, apologies.

Worth noting: `run` seems to be "All Foot Sports" (i.e. run, trail run, walk, hike, virtual run) whereas `sport_Run` seems to be strictly runs.

Unfortunately I do not have a Strava Premium subscription to test these.

**Comment by erik** [comment]
> I should have been able to figure that myself, apologies.

No worries, I wouldn't be aware of the change otherwise!
